### ISSUE TITLE
Will this continue as source of the Faker library?

### ISSUE THREAD

**Issue by Geertvdc** [withshepherd/faker.js#1]
I noticed this morning that the original faker repo and npm package were all removed or emptied (https://github.com/Marak/Faker.js). Looking for a fork or alternative I bumped into this.

Will you continue building / supporting faker.js? Do you need any help? Could you elaborate on the plans? Did you know Marak?

I think Faker.js by Marak was a well used library and it would be a shame if it would go away. I would love helping out in getting this back up if you need any help.

**Comment by mmahalwy** [comment]
Also, might be a good idea to add some of these answers to the README as I am sure others are thinking the same.

**Comment by deepakgrewal** [comment]
Would love to support this too. Updated the Readme with a [pull request here](https://github.com/withshepherd/faker.js/pull/3)

**Comment by katsanva** [comment]
Would like to help with ts part, any suggestions?

**Comment by mmahalwy** [comment]
Yes! I can create some issues if y'all would like to help! cc @katsanva @deepakgrewal @Geertvdc 

Thanks @jwalton for already jumping in and helping!

**Comment by zactopus** [comment]
Does Shepard plan to pay Marak for his work? https://github.com/sponsors/Marak

One of the things Marak brought up multiple times was that companies were using his work without paying him.

**Comment by g45t345rt** [comment]
Hi guys! I've already created a version of faker last month.
It's far from being the same thing but it does the same job and support ESM.

https://github.com/g45t345rt/minifaker
https://www.npmjs.com/package/minifaker

It's missing a lot of locales and other functions but I plan to add more and more over time certainly if people start using it more.

**Comment by mmahalwy** [comment]
@g45t345rt this looks awesome and frankly the direction i'd love to see faker go (ts, tree-shaking, and more). I noticed your package would cause breaking changes as many of the functions are no longer nested. Would you be open to either porting over some of the work here?

**Comment by g45t345rt** [comment]
You're right my package is not made for a quick direct replacement. You would have to change your code and match the functions :S It's good for new projects or people that don't mind changing their code.

The reason why I did not put functions in nested categories is simply because it's easier to find them with the intellisense.

For example:
`minifaker.bitcoinAddress()`
`faker.finance.bitcoinAddress()` // You have to know that it's in the finance category

As for porting over some of the work. I don't really know what I could bring since I'm doing the opposite :S
Also, in my opinion, changing faker to Typescript and using ESM is doable but it's just too much work for not a lot of benefits.

Anyway, thanks for keeping the project alive!

**Comment by owex** [comment]
Honestly i'd rename this repo to **jsfaker** or something so as to give it a fresh start and to avoid any confusion/conflict on npm

**Comment by Geertvdc** [comment]
I agree with @owex that this reincarnation of the Faker.js library should probably change it name so we don't "Steal" the stuff Marak made. Although it had the MIT license doesn't mean we should just continue as nothing happened. 

The name should imo be close to the original name and have a clear reference in the readme that this is the continuation of the original Faker.js

We won't have access to his NPM package anyway so on NPM it will have to go under a different name. In NPM the package was called `faker` and the repo called `faker.js`

I think `faker-js` or `fakerjs` would fit best. `jsfaker` for me doesn't sound right. If you change the repo name to either one of these you can also name the npm package the same as the repo which is always good for findability.

**Comment by JeffBeltran** [comment]
Wanted to throw this out here, happy to offer up https://github.com/JeffBeltran/faker.js-docs to include in the project. tried to get this merged into default project at least on the readme but that was a big no no from the previous maintainer but feel free to add the URL to the readme if that will help: https://fakerjsdocs.netlify.app/

**Comment by ashmortar** [comment]
Just wanted to hop in and say that I'd love to help out in any way I can, and I think the idea of converting to typescript is great!

**Comment by nikolalukovic** [comment]
I volunteer to help. Is there any Discord or something similar to coordinate?

**Comment by luciferreeves** [comment]
Actually, I forked from this repo and created "bluffmaster", so that it has some unique name on npm. Its easy to type `npm i bluffmaster` instead of something like `npm i sumeuser/faker` or `npm i faker-community-version`. Here are the links:
Github Link: https://github.com/luciferreeves/bluffmaster
NPM: https://www.npmjs.com/package/bluffmaster

**Comment by mmahalwy** [comment]
fwiw, we tried different combos of faker - either they were taken or npm flagged them as too similar. figured @withshepherd/faker.js was different enough 🤷

**Comment by mmahalwy** [comment]
> Wanted to throw this out here, happy to offer up https://github.com/JeffBeltran/faker.js-docs to include in the project. tried to get this merged into default project at least on the readme but that was a big no no from the previous maintainer but feel free to add the URL to the readme if that will help: https://fakerjsdocs.netlify.app/


@JeffBeltran sounds awesome! want to open a pr?

**Comment by doughlass** [comment]
@mmahalwy is there a Slack or Discord we could create for the community? Porting to TS is on my high list of to-do's

**Comment by damienwebdev** [comment]
As a comment, I have a much further forward of the fork here: https://github.com/graycoreio/faker.js

**Comment by chuckrincon** [comment]
I volunteer to help keep this project alive.

I agree with @Geertvdc
> I think faker-js or fakerjs would fit best. jsfaker for me doesn't sound right. If you change the repo name to either one of these you can also name the npm package the same as the repo which is always good for findability.

Creating an ORG account and porting the project like the [fakerPHP](https://github.com/fakerphp) people did could be the best.
With this approach we could isolate the locale dependencies as well the `fakerjs.github.io` docs site.

Although, [the `faker-js` ORG account was created 2 days ago](https://github.com/faker-js) and the only committer is @prisis, maybe we could try to contact him and ask if he is willing to help.
[The `fakerjs` ORG account](https://github.com/fakerjs) is also taken, but it seems to be abandoned.

**Comment by prisis** [comment]
Hey :), if you want, I can give you the org :)

**Comment by Shinigami92** [comment]
> Hey :), if you want, I can give you the org :)

This would be awesome and show package users that this version it the way to go and now a fully community driven project instead of random fork from someone with version xy and this has this feature but not the one of other random fork :sweat_smile: 

I would love to have :one: **true successor** :raised_hands:

**Comment by clarkerican** [comment]
> > Hey :), if you want, I can give you the org :)
> 
> This would be awesome and show package users that this version it the way to go and now a fully community driven project instead of random fork from someone with version xy and this has this feature but not the one of other random fork 😅
> 
> I would love to have 1️⃣ **true successor** 🙌

Hey! I'm one of the engineers on the Shepherd team. We completely agree that having one true successor that the community is backing will be the best way forward. We totally support moving it over to a community org and allowing it to be community-driven.  I'm happy to help where I can in this transition and with the project moving forward 😄

**Comment by mmahalwy** [comment]
Ditto what @clarkerican wrote! We'd love to take you on the offer @prisor! Want to email me: mo@withshepherd.com?

**Comment by prisis** [comment]
@[**mmahalwy**](https://github.com/mmahalwy) **only if you write my name correctly :P**

**Comment by prisis** [comment]
Invited @mmahalwy as owner and @clarkerican  ad member :)

**Comment by damienwebdev** [comment]
@prisis could you add me as well? My org @graycoreio has a more recent fork ~300+ commits ahead https://github.com/graycoreio/faker.js as well as some fixes for failing tests that  we'd like to merge but would want external community review on - https://github.com/graycoreio/faker.js/pulls

**Comment by JeffBeltran** [comment]
> > Wanted to throw this out here, happy to offer up https://github.com/JeffBeltran/faker.js-docs to include in the project. tried to get this merged into default project at least on the readme but that was a big no no from the previous maintainer but feel free to add the URL to the readme if that will help: https://fakerjsdocs.netlify.app/
> 
> @JeffBeltran sounds awesome! want to open a pr?

yeah i mean it will just be a link on the readme for now until things get sorted

**Comment by mmahalwy** [comment]
@prisis really sorry, I was on mobile (at wedding 😇) and it auto corrected. Sorry about that

**Comment by mmahalwy** [comment]
And just to jump in quick here. We want to:
- Move to its own org
- Grab commits from the latest as this fork is slightly behind

**Comment by damienwebdev** [comment]
@mmahalwy this has already been moved to the https://github.com/faker-js/faker.js repo. We just need to re-play your commits onto that `HEAD` and start to move forward from there. I think this repo should be redirect to the new community fork. You're the owner of that new org/repo anyways, so it should be easy. 

I don't have review/merge ownership [in that repo ](https://github.com/faker-js/faker.js) but once I do, I think we can make some good headway on getting infra up and running.

**Comment by blikblum** [comment]
> We won't have access to his NPM package anyway so on NPM it will have to go under a different name. In NPM the package was called `faker` and the repo called `faker.js`
> 
> I think `faker-js` or `fakerjs` would fit best. `jsfaker` for me doesn't sound right. If you change the repo name to either one of these you can also name the npm package the same as the repo which is always good for findability.

Maybe rename to `refaker` ?

**Comment by nikolalukovic** [comment]
Maybe just keep it simple and call it faker2? It will evolve into something else anyways considering the situation.

**Comment by Shinigami92** [comment]
@mmahalwy @clarkerican 
I would suggest to archive this repo now and write a link into README.md to new home https://github.com/faker-js/faker.js

**Comment by mmahalwy** [comment]
Hey all, this is now at https://github.com/faker-js/faker.js. We will be cutting 6.0.0 very soon with latest commits from the original repo. Going to close this issue and create a new one in the new repo
