### ISSUE TITLE
Copyright removal

### ISSUE THREAD

**Issue by galactic-src** [withshepherd/faker.js#15]
This commit https://github.com/withshepherd/faker.js/commit/f25607e5cc8a8c9c5c4c30e7a302a5c8e5f977a5 removed a copyright notice from the previous maintainer which stated the terms under which this code could be used, and which explicitly stated the copyright should remain:

```
#### Marak Squires

faker.js - Copyright (c) 2020
Marak Squires
www.marak.com
http://github.com/marak/faker.js/

faker.js was inspired by and has used data definitions from:

 * <https://github.com/stympy/faker/> - Copyright (c) 2007-2010 Benjamin Curtis
 * <http://search.cpan.org/~jasonk/Data-Faker-0.07/> - Copyright 2004-2005 by Jason Kohles

Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject to
the following conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

```

I'd suggest that should be respected and reinstated, given the context.

**Comment by ItsCEED** [comment]
If the current fork doesn't return this ill make sure this will go down.

**Comment by lallenfrancisl** [comment]
Removing the copyright is disrespectful and against the spirit of opensource. No matter what happened, all the code that's now in the repo was majorly contributed by Marak

**Comment by IanVS** [comment]
The license still exists: https://github.com/withshepherd/faker.js/blob/master/MIT-LICENSE.txt

**Comment by galactic-src** [comment]
@IanVS Thank you :relieved: That file also includes the copyright and message summarising conditions of reuse.

Closing this issue
