### ISSUE TITLE
Looking to fork this version of Faker.js directly into Faker Extra

### ISSUE THREAD

**Issue by schalkventer** [withshepherd/faker.js#17]
I'm the maintainer of the [`faker-extra`](https://www.npmjs.com/package/faker-extra) library, obviously the recent development has been a bit of a head-ache for me. This repo looks to be the most promising of all the direct Faker forks. 

I order to prevent this situation from happening again I'm looking to manually build this fork directly into `faker-extra`. Just checking if you are happy with this @withshepared? Also happy to add you and anyone else interested in helping with this as contributors to `faker-extra`.

**Comment by clarkerican** [comment]
Hey @schalkventer , as per the conversation in this issue: https://github.com/withshepherd/faker.js/issues/1#issue-1094203363, we're looking to move the official fork over to https://github.com/faker-js/faker.js. I'd recommend moving this post over there :)

**Comment by schalkventer** [comment]
Great! Thanks @clarkerican! 🙏
